package com.example.util;

import java.util.concurrent.atomic.AtomicInteger;

public class AutogeneratedNumber {
	private static AtomicInteger id = new AtomicInteger(-1);
	public static int getNext(){
		return id.incrementAndGet();
	}
}
