package com.example.util;

import java.util.List;

public class ShoppingBasket {
	private int id = AutogeneratedNumber.getNext();

	public ShoppingBasket(){
		System.out.println("New shopping basket created..");
	}
	private List boughtItems;

	public int getId() {
		return id;
	}

}
