CREATE TABLE CARS_COMPOSITE_ORACLE
  (
    "COLOR"        VARCHAR2(255 BYTE),
    "PLATE_NO"     VARCHAR2(255 BYTE),
    "FK_PERSON_ID" NUMBER(*,0),
    "ENGINE_NUM"   VARCHAR2(20 BYTE),
    "MANUF_DATE" DATE,
    "COUNTRY" VARCHAR2(20 BYTE),
    constraint t_pk primary key (COLOR,PLATE_NO,FK_PERSON_ID,ENGINE_NUM,MANUF_DATE,COUNTRY)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
  commit;