create table orders(
	  orderId bigint generated by default as identity(start with 0) primary key, 
      customerId integer not null,
      price double not null,
	  orderCode varchar_ignorecase(50) not null
      );
create table movie(
	  id bigint generated by default as identity(start with 0) primary key, 
      title varchar_ignorecase(50) not null,
      stars varchar_ignorecase(50) not null
      );